### ISSUE TITLE
Create repo for online soures to replace our theory slides

### ISSUE THREAD

**Issue by MartenBE** [HOGENT-MLOps/mlops-slides#13]
## Modules

- [x] Module 1: Martijn
- [x] Module 2: Martijn
- [x] Module 3: Thomas
- [x] Module 4: Thomas
- [x] Module 5: Thomas
- [x] Module 6: Martijn

**Comment by MartenBE** [comment]
Main has been set to MkDocs.

**Comment by MartenBE** [comment]
Guess we did it

**Comment by thomasaelbrecht** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzg3Njl0OG5wMzlyZjhjaGo2YjN0cjUxbGs4bHZwNHdrZmNqZzB3cCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/Sculsk7YRnRpvMZrR3/giphy.gif)
